

---
  spring:
    thymeleaf:
      prefix: resources/templates/
      suffix: .html
      enabled: true
      encoding: UTF-8
      check-template-location: false
#    datasource:
#      url: jdbc:mariadb://localhost:3306/springbootwebservice
#      driver-class-name: org.mariadb.jdbc.Driver
#      username: root
#      password: root
